export const ADD_ARTICLE = 'ADD_ARTICLE';
export const BASIC_ACTION = 'BASIC_ACTION';
export const FETCH_COUNTRY_SERVEASES = 'FETCH_COUNTRY_CODES';
export const ADD_COUNTRY_CODE = 'ADD_COUNTRY_CODE';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';